version: '3'

services:
  terraform:
    image: hashicorp/terraform:1.2.9
    volumes:
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
      - ./:/app/
      - ./vendor:/app/vendor
    working_dir: /app/
    network_mode: bridge
