version: '3'

services:
  terraform:
    image: hashicorp/terraform:1.2.9
    volumes:
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
      - ./modules:/stacks/modules
      - ./${SCOPE}:/stacks/${SCOPE}
      - ./vendor:/stacks/vendor
    working_dir: /stacks/${SCOPE}
    network_mode: bridge
